<?php
/**
 * Contao 
 * German translation file 
 * 
 * copyright  Tim Gatzky 2013 
 * author     Tim Gatzky <info@tim-gatzky.de>
 * Translator:  
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['MSC']['readerpaginations']['first']         	= '&#171; Anfang';
$GLOBALS['TL_LANG']['MSC']['readerpaginations']['previous']      	= 'Zurück';
$GLOBALS['TL_LANG']['MSC']['readerpaginations']['next']  	       	= 'Vorwärts';
$GLOBALS['TL_LANG']['MSC']['readerpaginations']['last']				= 'Ende &#187;';
$GLOBALS['TL_LANG']['MSC']['readerpaginations']['total']  	  		= '%s von %s';
$GLOBALS['TL_LANG']['MSC']['readerpaginations']['goTo']	    		= 'Gehe zu %s';
