<?php
/**
 * Contao 
 * German translation file 
 * 
 * copyright  Tim Gatzky 2013 
 * author     Tim Gatzky <info@tim-gatzky.de>
 * Translator:  
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */

/**
 * Fields
 */
$GLOBALS['TL_LANG']['tl_module']['addReaderPagination']						= array('Pagination hinzufügen', 'Dem Leser-Modul eine Pagination zum Durchblättern hinzufügen');
$GLOBALS['TL_LANG']['tl_module']['readerpagination_template'] 				= array('Layout-Template', 'Hier können Sie das Paginations-Template auswählen.');
$GLOBALS['TL_LANG']['tl_module']['readerpagination_numberOfLinks'] 			= array('Anzahl an Links', 'Legen Sie fest wieviele Links angezeigt werden.');
$GLOBALS['TL_LANG']['tl_module']['readerpagination_format'] 				= array('Anzeigeformat', 'Hier können Sie das Anzeigeformat/die Spannweite der Pagination auswählen.');
$GLOBALS['TL_LANG']['tl_module']['readerpagination_catalogTitleField'] 		= array('Titelfeld', 'Bitte wählen Sie das Feld, das als Referenz für die Bildung des Link-Titels genutzt werden soll');
$GLOBALS['TL_LANG']['tl_module']['catalog_where']['1'] .= ' Die Sortierreihenfolge ändern Sie mit z.B. ORDER BY meinFeld ASC. Mehrere Einträge mit AND verknüpfen.';

/**
 * References
 */
#$GLOBALS['TL_LANG']['tl_module']['readerpagination_format']['cal_list']		= 'Pagination Spannweite';
$GLOBALS['TL_LANG']['tl_module']['readerpagination_format']['cal_month']	= 'Aktueller Monat';
$GLOBALS['TL_LANG']['tl_module']['readerpagination_format']['cal_year']		= 'Aktuelles Jahr';
$GLOBALS['TL_LANG']['tl_module']['readerpagination_format']['cal_all']		= 'Alle Events';
#$GLOBALS['TL_LANG']['tl_module']['readerpagination_format']['news_list']	= 'Pagination Spannweite';
$GLOBALS['TL_LANG']['tl_module']['readerpagination_format']['news_month']	= 'Aktueller Monat';
$GLOBALS['TL_LANG']['tl_module']['readerpagination_format']['news_year']	= 'Aktuelles Jahr';
$GLOBALS['TL_LANG']['tl_module']['readerpagination_format']['news_all']		= 'Alle Beträge';
$GLOBALS['TL_LANG']['tl_module']['readerpagination_format']['cat_month']	= 'Aktueller Monat';
$GLOBALS['TL_LANG']['tl_module']['readerpagination_format']['cat_year']		= 'Aktuelles Jahr';
$GLOBALS['TL_LANG']['tl_module']['readerpagination_format']['cat_all']		= 'Alle Einträge';

/**
 * Legends
 */
$GLOBALS['TL_LANG']['tl_module']['readerpagination_legend'] 	= 'Paginations-Einstellungen';