<?php
/**
 * Contao 
 * English translation file 
 * 
 * copyright  Tim Gatzky 2013 
 * author     Tim Gatzky <info@tim-gatzky.de>
 * Translator:  
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */

$GLOBALS['TL_LANG']['MSC']['readerpaginations']['first']         	= '&#171; Begin';
$GLOBALS['TL_LANG']['MSC']['readerpaginations']['previous']      	= 'Previous';
$GLOBALS['TL_LANG']['MSC']['readerpaginations']['next']  	       	= 'Next';
$GLOBALS['TL_LANG']['MSC']['readerpaginations']['last']				= 'End &#187;';
$GLOBALS['TL_LANG']['MSC']['readerpaginations']['total']  	  		= '%s of %s';
$GLOBALS['TL_LANG']['MSC']['readerpaginations']['goTo']	    		= 'Go to %s';