<?php
/**
 * Contao 
 * English translation file 
 * 
 * copyright  Tim Gatzky 2013 
 * author     Tim Gatzky <info@tim-gatzky.de>
 * Translator:  
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */

/**
 * Fields
 */
$GLOBALS['TL_LANG']['tl_module']['addReaderPagination']						= array('Add a Pagination', 'Add a pagination to walk through items');
$GLOBALS['TL_LANG']['tl_module']['readerpagination_template'] 				= array('Layout-Template', 'Choose your custom pagination template.');
$GLOBALS['TL_LANG']['tl_module']['readerpagination_numberOfLinks'] 			= array('Number of links', 'Choose the number of links.');
$GLOBALS['TL_LANG']['tl_module']['readerpagination_format'] 				= array('Scope', 'Choose the date format/date scope of the pagination');
$GLOBALS['TL_LANG']['tl_module']['catalog_where']['1'] .= ' The sort order can be changed by e.g. ORDER BY myFeld ASC. Connect statements with an AND .';


/**
 * References
 */
#$GLOBALS['TL_LANG']['tl_module']['readerpagination_format']['cal_list']		= 'Pagination Spannweite';
$GLOBALS['TL_LANG']['tl_module']['readerpagination_format']['cal_month']	= 'Current month';
$GLOBALS['TL_LANG']['tl_module']['readerpagination_format']['cal_year']		= 'Current year';
$GLOBALS['TL_LANG']['tl_module']['readerpagination_format']['cal_all']		= 'All events';
#$GLOBALS['TL_LANG']['tl_module']['readerpagination_format']['news_list']	= 'Pagination Spannweite';
$GLOBALS['TL_LANG']['tl_module']['readerpagination_format']['news_month']	= 'Current month';
$GLOBALS['TL_LANG']['tl_module']['readerpagination_format']['news_year']	= 'Current year';
$GLOBALS['TL_LANG']['tl_module']['readerpagination_format']['news_all']		= 'All posts';
$GLOBALS['TL_LANG']['tl_module']['readerpagination_format']['cat_month']	= 'Current month';
$GLOBALS['TL_LANG']['tl_module']['readerpagination_format']['cat_year']		= 'Current year';
$GLOBALS['TL_LANG']['tl_module']['readerpagination_format']['cat_all']		= 'All entries';

/**
 * Legends
 */
$GLOBALS['TL_LANG']['tl_module']['readerpagination_legend'] 	= 'Paginations-Settings';