<?php
/**
 * Contao 
 * English translation file 
 * 
 * copyright  Tim Gatzky 2013 
 * author     Tim Gatzky <info@tim-gatzky.de>
 * Translator:  
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */

/**
 * Fields
 */
$GLOBALS['TL_LANG']['tl_news']['hide_in_pagination'] = array('Hide in Pagination', 'Do not show this post in the pagination.');